import type { ThemeConfig } from "antd";
import { theme } from "antd";

export const lorecraft = {
  color: {
    surface: "#131313",
    surfaceDim: "#131313",
    surfaceBright: "#393939",
    surfaceContainerLowest: "#0e0e0e",
    surfaceContainerLow: "#1c1b1b",
    surfaceContainer: "#201f1f",
    surfaceContainerHigh: "#2a2a2a",
    surfaceContainerHighest: "#353534",
    surfaceVariant: "#353534",
    onSurface: "#e5e2e1",
    onSurfaceVariant: "#d0c5af",
    outline: "#99907c",
    outlineVariant: "#4d4635",
    primary: "#f2ca50",
    primaryContainer: "#d4af37",
    onPrimary: "#3c2f00",
    primaryFixed: "#ffe088",
    inversePrimary: "#735c00",
    secondary: "#c9bfff",
    secondaryAccent: "#6d4aff",
    secondaryContainer: "#4709db",
    onSecondary: "#2f009c",
    tertiary: "#d0cdcd",
    onTertiary: "#303030",
    error: "#ffb4ab",
    errorContainer: "#93000a",
    onError: "#690005",
    success: "#31d86f",
  },
  font: {
    ui: `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`,
    heading: `"Hanken Grotesk", "Inter", system-ui, sans-serif`,
    lore: `"Source Serif Four", Georgia, serif`,
  },
} as const;

const color = lorecraft.color;

const lorecraftDarkAlgorithm: NonNullable<ThemeConfig["algorithm"]> = (
  seedToken,
  derivativeToken,
) => ({
  ...theme.darkAlgorithm(seedToken, derivativeToken),
  colorPrimary: color.primaryContainer,
});

export const lorecraftAntdTheme = {
  algorithm: lorecraftDarkAlgorithm,
  cssVar: {
    key: "lorecraft",
  },
  token: {
    colorPrimary: color.primaryContainer,
    colorPrimaryBg: "rgba(212, 175, 55, 0.12)",
    colorPrimaryBgHover: "rgba(212, 175, 55, 0.18)",
    colorPrimaryBorder: color.inversePrimary,
    colorPrimaryBorderHover: color.primary,
    colorPrimaryHover: color.primary,
    colorPrimaryActive: "#b4932f",
    colorPrimaryText: color.primary,
    colorPrimaryTextHover: color.primaryFixed,
    colorPrimaryTextActive: color.primaryContainer,

    colorInfo: color.secondaryAccent,
    colorInfoBg: "rgba(109, 74, 255, 0.14)",
    colorInfoBorder: "rgba(201, 191, 255, 0.34)",
    colorInfoText: color.secondary,
    colorSuccess: color.success,
    colorWarning: color.primary,
    colorError: color.error,
    colorErrorBg: "rgba(147, 0, 10, 0.22)",
    colorErrorBorder: color.errorContainer,
    colorErrorText: color.error,

    colorBgBase: color.surface,
    colorBgLayout: color.surfaceContainerLowest,
    colorBgContainer: color.surfaceContainerLow,
    colorBgElevated: color.surfaceContainer,
    colorBgSpotlight: color.surfaceContainerLowest,
    colorBgContainerDisabled: color.surfaceContainer,
    colorBgTextHover: "rgba(229, 226, 225, 0.06)",
    colorBgTextActive: "rgba(212, 175, 55, 0.14)",

    colorFill: "rgba(229, 226, 225, 0.14)",
    colorFillSecondary: "rgba(229, 226, 225, 0.10)",
    colorFillTertiary: "rgba(229, 226, 225, 0.06)",
    colorFillQuaternary: "rgba(229, 226, 225, 0.04)",
    colorFillAlter: color.surfaceContainer,
    colorFillContent: color.surfaceContainer,
    colorFillContentHover: color.surfaceContainerHigh,

    colorText: color.onSurface,
    colorTextHeading: color.onSurface,
    colorTextSecondary: color.onSurfaceVariant,
    colorTextTertiary: color.outline,
    colorTextQuaternary: "rgba(208, 197, 175, 0.48)",
    colorTextDescription: color.onSurfaceVariant,
    colorTextLabel: color.onSurfaceVariant,
    colorTextPlaceholder: "rgba(208, 197, 175, 0.54)",
    colorTextDisabled: "rgba(208, 197, 175, 0.36)",
    colorTextLightSolid: color.onPrimary,
    colorIcon: color.onSurfaceVariant,
    colorIconHover: color.primary,
    colorHighlight: color.primary,

    colorBorder: color.outlineVariant,
    colorBorderSecondary: "rgba(153, 144, 124, 0.28)",
    colorBorderBg: color.surfaceContainerLowest,
    colorSplit: "rgba(153, 144, 124, 0.22)",

    fontFamily: lorecraft.font.ui,
    fontFamilyCode: `"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace`,
    fontSize: 16,
    fontSizeSM: 12,
    fontSizeLG: 18,
    fontSizeXL: 24,
    fontWeightStrong: 600,
    lineHeight: 1.5,

    borderRadiusXS: 4,
    borderRadiusSM: 4,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusOuter: 16,

    controlHeightSM: 32,
    controlHeight: 40,
    controlHeightLG: 48,
    controlOutline: "rgba(212, 175, 55, 0.18)",
    controlOutlineWidth: 2,
    controlItemBgHover: color.surfaceContainerHigh,
    controlItemBgActive: "rgba(212, 175, 55, 0.14)",
    controlItemBgActiveHover: "rgba(212, 175, 55, 0.20)",

    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 20,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 40,

    boxShadow: "none",
    boxShadowSecondary: "none",
    boxShadowTertiary: "none",
  },
  components: {
    Layout: {
      bodyBg: color.surfaceContainerLowest,
      headerBg: color.surfaceContainerLowest,
      siderBg: color.surfaceContainerLow,
      footerBg: color.surfaceContainerLowest,
      triggerBg: color.surfaceContainer,
      triggerColor: color.onSurfaceVariant,
      headerColor: color.onSurface,
    },
    Button: {
      borderRadius: 8,
      fontWeight: 600,
      colorPrimary: color.primaryContainer,
      colorPrimaryHover: color.primary,
      colorPrimaryActive: "#b4932f",
      primaryColor: color.onPrimary,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBg: "transparent",
      defaultColor: color.onSurfaceVariant,
      defaultBorderColor: color.outlineVariant,
      defaultHoverBg: "rgba(212, 175, 55, 0.08)",
      defaultHoverColor: color.primary,
      defaultHoverBorderColor: color.outline,
      defaultActiveBg: "rgba(212, 175, 55, 0.14)",
      defaultActiveColor: color.primary,
      defaultActiveBorderColor: color.primaryContainer,
      textTextColor: color.onSurfaceVariant,
      textTextHoverColor: color.primary,
      textTextActiveColor: color.primaryContainer,
      textHoverBg: "rgba(229, 226, 225, 0.06)",
      paddingInline: 18,
      paddingInlineLG: 22,
    },
    Card: {
      colorBgContainer: color.surfaceContainerLow,
      colorBorderSecondary: color.outlineVariant,
      headerBg: color.surfaceContainerLow,
      actionsBg: color.surfaceContainer,
      extraColor: color.primary,
      bodyPadding: 24,
      headerPadding: 20,
      borderRadiusLG: 12,
    },
    Input: {
      colorBgContainer: color.surface,
      colorText: color.onSurface,
      colorTextPlaceholder: "rgba(208, 197, 175, 0.54)",
      colorBorder: color.outlineVariant,
      hoverBg: color.surface,
      activeBg: color.surface,
      hoverBorderColor: color.outline,
      activeBorderColor: color.primaryContainer,
      activeShadow: "0 0 0 3px rgba(212, 175, 55, 0.12)",
      paddingInline: 12,
      paddingBlock: 7,
    },
    InputNumber: {
      colorBgContainer: color.surface,
      colorText: color.onSurface,
      colorTextPlaceholder: "rgba(208, 197, 175, 0.54)",
      colorBorder: color.outlineVariant,
      hoverBorderColor: color.outline,
      activeBorderColor: color.primaryContainer,
      activeShadow: "0 0 0 3px rgba(212, 175, 55, 0.12)",
    },
    Select: {
      selectorBg: color.surface,
      colorBgElevated: color.surfaceContainer,
      colorBorder: color.outlineVariant,
      colorText: color.onSurface,
      colorTextPlaceholder: "rgba(208, 197, 175, 0.54)",
      optionActiveBg: color.surfaceContainerHigh,
      optionSelectedBg: "rgba(212, 175, 55, 0.14)",
      optionSelectedColor: color.primary,
      optionSelectedFontWeight: 600,
      hoverBorderColor: color.outline,
      activeBorderColor: color.primaryContainer,
      activeOutlineColor: "rgba(212, 175, 55, 0.16)",
    },
    Menu: {
      itemBg: color.surfaceContainerLow,
      itemColor: color.onSurfaceVariant,
      itemHoverBg: color.surfaceContainerHigh,
      itemHoverColor: color.onSurface,
      itemSelectedBg: color.surfaceContainerHighest,
      itemSelectedColor: color.primary,
      itemActiveBg: "rgba(212, 175, 55, 0.12)",
      groupTitleColor: color.onSurfaceVariant,
      subMenuItemBg: color.surfaceContainerLow,
      popupBg: color.surfaceContainer,
      darkItemBg: color.surfaceContainerLow,
      darkSubMenuItemBg: color.surfaceContainerLow,
      darkItemColor: color.onSurfaceVariant,
      darkItemHoverBg: color.surfaceContainerHigh,
      darkItemHoverColor: color.onSurface,
      darkItemSelectedBg: color.surfaceContainerHighest,
      darkItemSelectedColor: color.primary,
      darkGroupTitleColor: color.onSurfaceVariant,
      itemBorderRadius: 8,
      itemHeight: 48,
      iconSize: 20,
      collapsedIconSize: 20,
      activeBarWidth: 3,
    },
    Dropdown: {
      colorBgElevated: "rgba(32, 31, 31, 0.98)",
      colorBorder: color.outlineVariant,
      controlItemBgHover: color.surfaceContainerHigh,
      borderRadiusLG: 12,
      boxShadowSecondary: "none",
    },
    Popover: {
      colorBgElevated: "rgba(32, 31, 31, 0.98)",
      colorBorder: color.outlineVariant,
      colorText: color.onSurface,
      borderRadiusLG: 12,
      boxShadowSecondary: "none",
    },
    Tooltip: {
      colorBgSpotlight: color.surfaceContainerLowest,
      colorTextLightSolid: color.onSurface,
      borderRadius: 8,
    },
    Modal: {
      contentBg: color.surfaceContainer,
      headerBg: color.surfaceContainer,
      footerBg: color.surfaceContainer,
      titleColor: color.onSurface,
      colorBgMask: "rgba(0, 0, 0, 0.72)",
      borderRadiusLG: 16,
      boxShadow: "none",
    },
    Drawer: {
      colorBgElevated: color.surfaceContainerLow,
      colorBgMask: "rgba(0, 0, 0, 0.68)",
    },
    Table: {
      colorBgContainer: color.surfaceContainerLow,
      headerBg: color.surfaceContainer,
      headerColor: color.onSurfaceVariant,
      headerSortActiveBg: color.surfaceContainerHigh,
      headerSortHoverBg: color.surfaceContainerHigh,
      rowHoverBg: color.surfaceContainerHigh,
      rowSelectedBg: "rgba(212, 175, 55, 0.12)",
      rowSelectedHoverBg: "rgba(212, 175, 55, 0.18)",
      borderColor: "rgba(153, 144, 124, 0.22)",
      footerBg: color.surfaceContainer,
      footerColor: color.onSurfaceVariant,
      headerBorderRadius: 8,
    },
    Tabs: {
      itemColor: color.onSurfaceVariant,
      itemHoverColor: color.primary,
      itemSelectedColor: color.primary,
      inkBarColor: color.primaryContainer,
    },
    Tag: {
      defaultBg: color.surface,
      defaultColor: color.onSurfaceVariant,
      colorBorder: color.outlineVariant,
      borderRadiusSM: 4,
    },
    Segmented: {
      itemColor: color.onSurfaceVariant,
      itemHoverColor: color.onSurface,
      itemHoverBg: color.surfaceContainerHigh,
      itemSelectedBg: color.surfaceContainerHighest,
      itemSelectedColor: color.primary,
      trackBg: color.surfaceContainer,
      trackPadding: 4,
    },
    Checkbox: {
      colorPrimary: color.primaryContainer,
      colorPrimaryHover: color.primary,
      colorBgContainer: color.surface,
      colorBorder: color.outlineVariant,
    },
    Radio: {
      colorPrimary: color.primaryContainer,
      colorPrimaryHover: color.primary,
      colorBgContainer: color.surface,
      colorBorder: color.outlineVariant,
    },
    Switch: {
      colorPrimary: color.primaryContainer,
      colorPrimaryHover: color.primary,
      colorTextQuaternary: color.surfaceContainerHighest,
      colorTextTertiary: color.surfaceBright,
    },
    Skeleton: {
      color: color.surfaceContainerHigh,
      colorGradientEnd: color.surfaceContainerHighest,
    },
    Divider: {
      colorSplit: "rgba(153, 144, 124, 0.22)",
    },
  },
} satisfies ThemeConfig;
