import type { ThemeConfig } from "antd";
import { theme } from "antd";

export const lorecraft = {
  color: {
    ink: "#0d0d0c",
    canvas: "#111110",
    sidebar: "#1b1a19",
    panel: "#171615",
    panelRaised: "#1f1e1c",
    panelHighest: "#2b2925",
    panelActive: "#3a3832",
    borderMuted: "#342f24",
    border: "#4d4635",
    borderStrong: "#6f654f",
    text: "#eee8dc",
    textSoft: "#cfc5b2",
    textMuted: "#9d927f",
    textSubtle: "#6f675a",
    primary: "#d9b437",
    primaryHover: "#f2ca50",
    primaryActive: "#b4932f",
    primarySoft: "rgba(217, 180, 55, 0.14)",
    primarySofter: "rgba(217, 180, 55, 0.08)",
    onPrimary: "#211904",
    info: "#9f91ff",
    success: "#57d982",
    warning: "#f2ca50",
    error: "#ff9f95",
  },
  font: {
    ui: `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`,
    heading: `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`,
    lore: `"Source Serif Four", Georgia, serif`,
  },
  radius: {
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
  },
  shadow: {
    focus: "0 0 0 3px rgba(217, 180, 55, 0.14)",
    elevated: "0 16px 40px rgba(0, 0, 0, 0.42)",
    floating: "0 10px 28px rgba(0, 0, 0, 0.36)",
  },
} as const;

const { color, radius, shadow } = lorecraft;

const lorecraftDarkAlgorithm: NonNullable<ThemeConfig["algorithm"]> = (
  seedToken,
  derivativeToken,
) => ({
  ...theme.darkAlgorithm(seedToken, derivativeToken),
  colorPrimary: color.primary,
});

export const lorecraftAntdTheme = {
  algorithm: lorecraftDarkAlgorithm,
  cssVar: {
    key: "lorecraft",
  },
  hashed: true,
  token: {
    colorPrimary: color.primary,
    colorPrimaryBg: color.primarySofter,
    colorPrimaryBgHover: color.primarySoft,
    colorPrimaryBorder: color.borderStrong,
    colorPrimaryBorderHover: color.primary,
    colorPrimaryHover: color.primaryHover,
    colorPrimaryActive: color.primaryActive,
    colorPrimaryText: color.primary,
    colorPrimaryTextHover: color.primaryHover,
    colorPrimaryTextActive: color.primary,

    colorInfo: color.info,
    colorInfoBg: "rgba(159, 145, 255, 0.12)",
    colorInfoBorder: "rgba(159, 145, 255, 0.32)",
    colorInfoText: "#c8c0ff",
    colorSuccess: color.success,
    colorSuccessBg: "rgba(87, 217, 130, 0.12)",
    colorSuccessBorder: "rgba(87, 217, 130, 0.3)",
    colorWarning: color.warning,
    colorWarningBg: "rgba(242, 202, 80, 0.12)",
    colorWarningBorder: "rgba(242, 202, 80, 0.32)",
    colorError: color.error,
    colorErrorBg: "rgba(255, 159, 149, 0.12)",
    colorErrorBorder: "rgba(255, 159, 149, 0.3)",
    colorErrorText: color.error,

    colorBgBase: color.canvas,
    colorBgLayout: color.ink,
    colorBgContainer: color.panel,
    colorBgElevated: color.panelRaised,
    colorBgSpotlight: color.panelHighest,
    colorBgContainerDisabled: color.panelRaised,
    colorBgTextHover: "rgba(238, 232, 220, 0.06)",
    colorBgTextActive: color.primarySoft,

    colorFill: "rgba(238, 232, 220, 0.12)",
    colorFillSecondary: "rgba(238, 232, 220, 0.09)",
    colorFillTertiary: "rgba(238, 232, 220, 0.06)",
    colorFillQuaternary: "rgba(238, 232, 220, 0.04)",
    colorFillAlter: color.panelRaised,
    colorFillContent: color.panelRaised,
    colorFillContentHover: color.panelHighest,

    colorText: color.text,
    colorTextHeading: color.text,
    colorTextSecondary: color.textSoft,
    colorTextTertiary: color.textMuted,
    colorTextQuaternary: color.textSubtle,
    colorTextDescription: color.textSoft,
    colorTextLabel: color.textSoft,
    colorTextPlaceholder: "rgba(207, 197, 178, 0.52)",
    colorTextDisabled: "rgba(207, 197, 178, 0.34)",
    colorTextLightSolid: color.onPrimary,
    colorIcon: color.textSoft,
    colorIconHover: color.primaryHover,
    colorHighlight: color.primary,

    colorBorder: color.border,
    colorBorderSecondary: color.borderMuted,
    colorBorderBg: color.ink,
    colorSplit: "rgba(77, 70, 53, 0.72)",

    fontFamily: lorecraft.font.ui,
    fontFamilyCode: `"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace`,
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontWeightStrong: 600,
    lineHeight: 1.45,
    lineHeightSM: 1.35,
    lineHeightLG: 1.5,

    borderRadiusXS: radius.xs,
    borderRadiusSM: radius.sm,
    borderRadius: radius.sm,
    borderRadiusLG: radius.md,
    borderRadiusOuter: radius.lg,

    controlHeightSM: 28,
    controlHeight: 32,
    controlHeightLG: 40,
    controlOutline: "rgba(217, 180, 55, 0.18)",
    controlOutlineWidth: 2,
    controlItemBgHover: color.panelHighest,
    controlItemBgActive: color.primarySoft,
    controlItemBgActiveHover: "rgba(217, 180, 55, 0.2)",

    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 20,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 48,

    boxShadow: shadow.elevated,
    boxShadowSecondary: shadow.floating,
    boxShadowTertiary: "0 6px 18px rgba(0, 0, 0, 0.3)",
  },
  components: {
    Alert: {
      borderRadiusLG: radius.md,
      defaultPadding: "10px 12px",
      withDescriptionPadding: "14px 16px",
    },
    Badge: {
      indicatorHeight: 18,
      indicatorHeightSM: 14,
      textFontSize: 11,
      textFontSizeSM: 10,
    },
    Button: {
      borderRadius: radius.xs,
      borderRadiusLG: radius.sm,
      borderRadiusSM: radius.xs,
      contentFontSize: 13,
      contentFontSizeLG: 14,
      contentFontSizeSM: 12,
      fontWeight: 600,
      colorPrimary: color.primary,
      colorPrimaryHover: color.primaryHover,
      colorPrimaryActive: color.primaryActive,
      primaryColor: color.onPrimary,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBg: "transparent",
      defaultColor: color.textSoft,
      defaultBorderColor: color.border,
      defaultHoverBg: color.primarySofter,
      defaultHoverColor: color.primaryHover,
      defaultHoverBorderColor: color.borderStrong,
      defaultActiveBg: color.primarySoft,
      defaultActiveColor: color.primary,
      defaultActiveBorderColor: color.primary,
      textTextColor: color.textSoft,
      textTextHoverColor: color.primaryHover,
      textTextActiveColor: color.primary,
      textHoverBg: "rgba(238, 232, 220, 0.06)",
      paddingInline: 14,
      paddingInlineLG: 18,
      paddingInlineSM: 10,
    },
    Card: {
      colorBgContainer: color.panel,
      colorBorderSecondary: color.borderMuted,
      headerBg: color.panel,
      actionsBg: color.panelRaised,
      extraColor: color.primary,
      bodyPadding: 16,
      bodyPaddingSM: 12,
      headerPadding: 16,
      headerPaddingSM: 12,
      borderRadiusLG: radius.md,
    },
    Checkbox: {
      colorPrimary: color.primary,
      colorPrimaryHover: color.primaryHover,
      colorBgContainer: color.canvas,
      colorBorder: color.border,
    },
    Collapse: {
      borderRadiusLG: radius.md,
      contentBg: color.panel,
      headerBg: color.panelRaised,
      headerPadding: "10px 12px",
    },
    Divider: {
      colorSplit: "rgba(77, 70, 53, 0.76)",
      marginLG: 24,
      margin: 16,
      marginXS: 8,
    },
    Drawer: {
      colorBgElevated: color.panelRaised,
      colorBgMask: "rgba(0, 0, 0, 0.68)",
      footerPaddingBlock: 12,
      footerPaddingInline: 16,
      zIndexPopup: 1000,
    },
    Dropdown: {
      colorBgElevated: "rgba(31, 30, 28, 0.98)",
      colorBorder: color.border,
      controlItemBgHover: color.panelHighest,
      borderRadiusLG: radius.md,
      boxShadowSecondary: shadow.floating,
    },
    Empty: {
      colorText: color.textSoft,
      colorTextDescription: color.textMuted,
    },
    Form: {
      itemMarginBottom: 16,
      labelColor: color.textSoft,
      labelRequiredMarkColor: color.primary,
    },
    Input: {
      colorBgContainer: color.canvas,
      colorText: color.text,
      colorTextPlaceholder: "rgba(207, 197, 178, 0.52)",
      colorBorder: color.border,
      hoverBg: color.canvas,
      activeBg: color.canvas,
      hoverBorderColor: color.borderStrong,
      activeBorderColor: color.primary,
      activeShadow: shadow.focus,
      paddingInline: 10,
      paddingBlock: 4,
    },
    InputNumber: {
      colorBgContainer: color.canvas,
      colorText: color.text,
      colorTextPlaceholder: "rgba(207, 197, 178, 0.52)",
      colorBorder: color.border,
      hoverBorderColor: color.borderStrong,
      activeBorderColor: color.primary,
      activeShadow: shadow.focus,
    },
    Layout: {
      bodyBg: color.ink,
      footerBg: color.ink,
      headerBg: color.canvas,
      headerColor: color.text,
      headerHeight: 48,
      headerPadding: "0 18px",
      siderBg: color.sidebar,
      triggerBg: color.panelRaised,
      triggerColor: color.textSoft,
    },
    Menu: {
      itemBg: color.sidebar,
      itemBorderRadius: 0,
      itemColor: color.textSoft,
      itemHeight: 40,
      itemHoverBg: color.panelHighest,
      itemHoverColor: color.text,
      itemMarginBlock: 3,
      itemMarginInline: 8,
      itemPaddingInline: 16,
      itemSelectedBg: color.panelActive,
      itemSelectedColor: color.primary,
      itemActiveBg: color.primarySofter,
      iconSize: 16,
      collapsedIconSize: 18,
      activeBarBorderWidth: 0,
      activeBarWidth: 3,
      groupTitleColor: color.textMuted,
      subMenuItemBg: color.sidebar,
      popupBg: color.panelRaised,
      darkItemBg: color.sidebar,
      darkSubMenuItemBg: color.sidebar,
      darkItemColor: color.textSoft,
      darkItemHoverBg: color.panelHighest,
      darkItemHoverColor: color.text,
      darkItemSelectedBg: color.panelActive,
      darkItemSelectedColor: color.primary,
      darkGroupTitleColor: color.textMuted,
    },
    Modal: {
      borderRadiusLG: radius.lg,
      boxShadow: shadow.elevated,
      colorBgMask: "rgba(0, 0, 0, 0.72)",
      contentBg: color.panelRaised,
      footerBg: color.panelRaised,
      headerBg: color.panelRaised,
      titleColor: color.text,
    },
    Popover: {
      colorBgElevated: "rgba(31, 30, 28, 0.98)",
      colorBorder: color.border,
      colorText: color.text,
      borderRadiusLG: radius.md,
      boxShadowSecondary: shadow.floating,
    },
    Radio: {
      colorPrimary: color.primary,
      colorPrimaryHover: color.primaryHover,
      colorBgContainer: color.canvas,
      colorBorder: color.border,
      buttonBg: "transparent",
      buttonCheckedBg: color.primarySoft,
      buttonColor: color.textSoft,
      buttonCheckedBgDisabled: color.panelHighest,
    },
    Segmented: {
      itemColor: color.textSoft,
      itemHoverColor: color.text,
      itemHoverBg: color.panelHighest,
      itemSelectedBg: color.panelActive,
      itemSelectedColor: color.primary,
      trackBg: color.panelRaised,
      trackPadding: 3,
    },
    Select: {
      selectorBg: color.canvas,
      colorBgElevated: color.panelRaised,
      colorBorder: color.border,
      colorText: color.text,
      colorTextPlaceholder: "rgba(207, 197, 178, 0.52)",
      optionActiveBg: color.panelHighest,
      optionSelectedBg: color.primarySoft,
      optionSelectedColor: color.primary,
      optionSelectedFontWeight: 600,
      hoverBorderColor: color.borderStrong,
      activeBorderColor: color.primary,
      activeOutlineColor: "rgba(217, 180, 55, 0.16)",
    },
    Skeleton: {
      color: color.panelHighest,
      colorGradientEnd: color.panelActive,
    },
    Switch: {
      colorPrimary: color.primary,
      colorPrimaryHover: color.primaryHover,
      colorTextQuaternary: color.panelActive,
      colorTextTertiary: color.borderStrong,
      handleBg: color.text,
      trackHeight: 18,
      trackMinWidth: 36,
      handleSize: 14,
    },
    Table: {
      borderColor: "rgba(77, 70, 53, 0.76)",
      cellFontSize: 13,
      cellPaddingBlock: 10,
      cellPaddingBlockSM: 8,
      cellPaddingInline: 12,
      cellPaddingInlineSM: 10,
      colorBgContainer: color.panel,
      footerBg: color.panelRaised,
      footerColor: color.textSoft,
      headerBg: color.panelRaised,
      headerBorderRadius: radius.sm,
      headerColor: color.textSoft,
      headerSortActiveBg: color.panelHighest,
      headerSortHoverBg: color.panelHighest,
      rowHoverBg: color.panelHighest,
      rowSelectedBg: color.primarySofter,
      rowSelectedHoverBg: color.primarySoft,
    },
    Tabs: {
      horizontalItemGutter: 24,
      horizontalMargin: "0 0 16px 0",
      inkBarColor: color.primary,
      itemColor: color.textSoft,
      itemHoverColor: color.primaryHover,
      itemSelectedColor: color.primary,
      titleFontSize: 13,
    },
    Tag: {
      borderRadiusSM: radius.xs,
      colorBorder: color.border,
      defaultBg: color.canvas,
      defaultColor: color.textSoft,
      fontSizeSM: 11,
      lineHeightSM: 1.35,
    },
    Tooltip: {
      borderRadius: radius.sm,
      colorBgSpotlight: color.panelHighest,
      colorTextLightSolid: color.text,
    },
    Typography: {
      titleMarginBottom: 8,
      titleMarginTop: 0,
    },
  },
} satisfies ThemeConfig;
